repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        -   id: trailing-whitespace
            stages: [commit]
        -   id: mixed-line-ending
            stages: [commit]
        -   id: check-json
            stages: [commit]
        -   id: check-toml
            stages: [commit]
        -   id: check-yaml
            stages: [commit]
        -   id: detect-private-key
        -   id: end-of-file-fixer
            stages: [commit]
        -   id: no-commit-to-branch
            args: [--branch, main]
  -   repo: local
      hooks:
        - id: format
          name: format
          entry: make format
          language: system
          types: [python]
          stages: [push]
        - id: pytest
          name: pytest
          entry: make test
          language: system
          always_run: true
          pass_filenames: false
          types: [python]
          stages: [push]
